'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useSelectedLayoutSegment } from 'next/navigation'
import TopMenu from "@/components/top-menu";
import FooterComponent from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });
/* 
export const metadata: Metadata = {
  title: "Gallery",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
  admin,
}: Readonly<{
  children: React.ReactNode;
  admin: React.ReactNode;
}>) {
  const token = "";

  return (
    <html lang="en">
      <body className={inter.className}>
        {token !== null ? admin :
          <>
            <TopMenu></TopMenu>
            {children}
            <FooterComponent></FooterComponent>
          </>
        }
      </body>
    </html>
  );
}
