'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { useSelectedLayoutSegment } from 'next/navigation'
import TopMenu from "@/components/top-menu";
import FooterComponent from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });
/* 
export const metadata: Metadata = {
  title: "Gallery",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
//   const token = window.localStorage.getItem('token');

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
       {/*  {token !== null ? admin :
          <>
            <TopMenu></TopMenu>
            {children}
            <FooterComponent></FooterComponent>
          </>
        } */}
      </body>
    </html>
  );
}
